/**
 * Postgres-native role provisioning.
 *
 * Generates the CREATE ROLE / GRANT statements that give a workspace member
 * their own real Postgres login at a chosen access level, instead of
 * everyone sharing one credential — the differentiator over app-level
 * "read-only" toggles, which an Advanced Mode user just bypasses in one
 * query. Like every other generator in this codebase (schemaDiff, schemaEdit,
 * indexAdvisor), nothing here executes: the statements go to the editor
 * behind the Run button.
 *
 * Assumes the connection provisioning *from* uses a credential that owns the
 * schema (or is superuser) — the same assumption a shared "admin credential"
 * implies. Levels, mapped to Postgres privileges:
 *
 *   read  — SELECT only, session forced read-only (`default_transaction_read_only`)
 *   write — read + INSERT/UPDATE/DELETE
 *   admin — write + DDL. Postgres has no per-schema "grant DDL rights" —
 *           altering or dropping objects you don't own requires ownership or
 *           membership in the owning role, so admin provisioning grants
 *           membership in the schema's owning role. That's the standard
 *           idiom, not a workaround.
 *   owner — not provisioned here; the owner already holds the credential
 *           used to provision everyone else.
 */

const crypto = require('crypto');
const { quoteIdent } = require('./identifier');

const LEVELS = ['read', 'write', 'admin'];

function generateRolePassword() {
  return crypto.randomBytes(18).toString('base64url');
}

/**
 * The role owning `schema` — needed for the admin level's "grant membership
 * in the owner" step. Read-only introspection, no caller input reaches SQL.
 */
async function getSchemaOwner(pool, schema) {
  const { rows } = await pool.query(
    `SELECT r.rolname AS owner
       FROM pg_namespace n
       JOIN pg_roles r ON r.oid = n.nspowner
      WHERE n.nspname = $1`,
    [schema],
  );
  return rows[0]?.owner || null;
}

/**
 * Pure: build the provisioning script. `password` is generated by the
 * caller (generateRolePassword()) so it can also be handed to the admin for
 * one-time hand-off to the teammate — this module only ever sees it as a
 * SQL literal to embed, never stores or transmits it.
 */
function buildProvisioningDdl({ schema, database, roleName, accessLevel, ownerRole, password }) {
  if (!LEVELS.includes(accessLevel)) {
    throw new Error(`Unsupported access level for role provisioning: ${accessLevel}`);
  }
  const role = quoteIdent(roleName);
  const schemaIdent = quoteIdent(schema);
  const statements = [
    `CREATE ROLE ${role} LOGIN PASSWORD '${password}';`,
    `GRANT CONNECT ON DATABASE ${quoteIdent(database)} TO ${role};`,
    `GRANT USAGE ON SCHEMA ${schemaIdent} TO ${role};`,
    `GRANT SELECT ON ALL TABLES IN SCHEMA ${schemaIdent} TO ${role};`,
    `ALTER DEFAULT PRIVILEGES IN SCHEMA ${schemaIdent} GRANT SELECT ON TABLES TO ${role};`,
  ];

  if (accessLevel === 'read') {
    statements.push(`ALTER ROLE ${role} SET default_transaction_read_only = on;`);
  }

  if (accessLevel === 'write' || accessLevel === 'admin') {
    statements.push(
      `GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${schemaIdent} TO ${role};`,
      `ALTER DEFAULT PRIVILEGES IN SCHEMA ${schemaIdent} GRANT INSERT, UPDATE, DELETE ON TABLES TO ${role};`,
    );
  }

  if (accessLevel === 'admin') {
    if (!ownerRole) throw new Error('admin provisioning requires the schema-owning role name');
    statements.push(
      `GRANT CREATE ON SCHEMA ${schemaIdent} TO ${role};`,
      `GRANT ${quoteIdent(ownerRole)} TO ${role};`,
    );
  }

  return { statements, destructive: false };
}

/** Removes a previously-provisioned role — e.g. when a member is removed or demoted. */
function buildDeprovisioningDdl(roleName) {
  return { statements: [`DROP ROLE IF EXISTS ${quoteIdent(roleName)};`], destructive: true };
}

module.exports = {
  LEVELS,
  generateRolePassword,
  getSchemaOwner,
  buildProvisioningDdl,
  buildDeprovisioningDdl,
};
